### ISSUE TITLE
apt-get-wrapper: Broken variable reference?

### ISSUE THREAD

**Issue by hartwork** [Whonix/whonixcheck#2]
Hi! Looking at https://github.com/Whonix/whonixcheck/blob/master/usr/lib/apt-get-wrapper#L48
```
[..]
line_lower_case="${line,,}"
first_two="${line_lower_case:0:2}"
if [ "$first_two_lower_case" = "e:" ]; then
  exit 125
fi
if [ "$first_two" = "w:" ]; then
[..]
```
I noticed, that `$first_two_lower_case` was probably meant to be `$first_two`. I don't see a definition of `$first_two_lower_case` anywhere.

**Comment by adrelanos** [comment]
Indeed. Fixed. Thanks!
